---
apiVersion: v1
kind: Secret
metadata:
  name: nutanix-creds
  namespace: kube-system
stringData:
  credentials: |
    [
      {
        "type": "basic_auth", 
        "data": { 
          "prismCentral":{
            "username": "$NUTANIX_USERNAME", 
            "password": "$NUTANIX_PASSWORD"
          },
          "prismElements": null
        }
      }
    ]
