{{- if eq .Values.createSecret true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
stringData:
  credentials: |
    [
      {
        "type": "basic_auth", 
        "data": {
          "prismCentral": {
            "username": {{ .Values.username | toJson }},
            "password": {{ .Values.password | toJson }}
          },
          "prismElements": null
        }
      }
    ]
{{- end }}