FROM registry.ci.openshift.org/openshift/release:golang-1.18 AS builder

WORKDIR /build
COPY . .
RUN make openshift-build

FROM registry.ci.openshift.org/ocp/4.12:base

LABEL description="Nutanix Cloud Controller Manager"

COPY --from=builder /build/bin/nutanix-cloud-controller-manager /bin/nutanix-cloud-controller-manager

ENTRYPOINT [ "/bin/nutanix-cloud-controller-manager" ]
