FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.15 AS builder

WORKDIR /build
COPY . .
RUN make openshift-build

FROM registry.ci.openshift.org/ocp/4.15:base

LABEL description="Nutanix Cloud Controller Manager"

COPY --from=builder /build/bin/nutanix-cloud-controller-manager /bin/nutanix-cloud-controller-manager

ENTRYPOINT [ "/bin/nutanix-cloud-controller-manager" ]
