FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.26-openshift-5.0 AS builder

WORKDIR /build
COPY . .
RUN make openshift-build

FROM registry.ci.openshift.org/ocp/5.0:base-rhel9

LABEL description="Nutanix Cloud Controller Manager"

COPY --from=builder /build/bin/nutanix-cloud-controller-manager /bin/nutanix-cloud-controller-manager

ENTRYPOINT [ "/bin/nutanix-cloud-controller-manager" ]
