name: Black Duck Policy Check
on:
  push:
    branches:
      - main
      - 'release-*'
  pull_request:
    paths:
      - '.github/**'
  pull_request_target:
    paths-ignore:
      - '.github/**'
jobs:
  security:
    if: github.repository == 'nutanix-cloud-native/cloud-provider-nutanix'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.head.sha }}"

      - name: Install devbox
        run: curl -fsSL https://get.jetpack.io/devbox | bash -s -- -f

      - name: Install devbox deps
        run: devbox install

      - name: Build Project
        run: devbox run -- make build

      - name: Run Synopsys Detect
        uses: synopsys-sig/detect-action@v0.3.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 8.10.0
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
